type PrefillEntry = { day: string; startTime: string; label: string; bg?: string; textColor?: string; disableClick?: boolean };

const imagePrefill: Record<string, PrefillEntry[]> = {
  DESCARTES: [
    { day: "Monday", startTime: "07:45", label: "UCSP" },
    { day: "Tuesday", startTime: "07:45", label: "UCSP" },
    { day: "Wednesday", startTime: "07:45", label: "UCSP" },
    { day: "Thursday", startTime: "07:45", label: "UCSP" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Thursday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Friday", startTime: "08:45", label: "PR1" },
    { day: "Monday", startTime: "10:00", label: "EIM" },
    { day: "Tuesday", startTime: "10:00", label: "HOPE F" },
    { day: "Wednesday", startTime: "10:00", label: "EIM" },
    { day: "Thursday", startTime: "10:00", label: "EIM" },
    { day: "Friday", startTime: "10:00", label: "EIM" },
    { day: "Monday", startTime: "11:00", label: "EIM" },
    { day: "Tuesday", startTime: "11:00", label: "PAGBASA" },
    { day: "Wednesday", startTime: "11:00", label: "EIM" },
    { day: "Thursday", startTime: "11:00", label: "EIM" },
    { day: "Friday", startTime: "11:00", label: "EIM" },
    { day: "Monday", startTime: "13:00", label: "PhySci" },
    { day: "Tuesday", startTime: "13:00", label: "PhySci" },
    { day: "Wednesday", startTime: "13:00", label: "PhySci" },
    { day: "Thursday", startTime: "13:00", label: "STAT" },
    { day: "Friday", startTime: "13:00", label: "PhySci" },
    { day: "Monday", startTime: "14:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "14:00", label: "STAT" },
    { day: "Wednesday", startTime: "14:00", label: "PR1" },
    { day: "Thursday", startTime: "14:00", label: "PR1" },
    { day: "Friday", startTime: "14:00", label: "STAT" },
    { day: "Monday", startTime: "15:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "15:00", label: "STAT" },
    { day: "Wednesday", startTime: "15:00", label: "PAGBASA" },
    { day: "Thursday", startTime: "15:00", label: "PR1" },
    { day: "Friday", startTime: "15:00", label: "HOPE F" },
  ],
  PHYTAGORAS: [
    { day: "Friday", startTime: "07:45", label: "STAT" },
    { day: "Friday", startTime: "08:45", label: "READING & WRTING" },
    { day: "Friday", startTime: "10:00", label: "BNC" },
    { day: "Friday", startTime: "11:00", label: "BNC" },
    { day: "Friday", startTime: "13:00", label: "UCSP" },
    { day: "Friday", startTime: "14:00", label: "PhySci" },
    { day: "Friday", startTime: "15:00", label: "PAGBASA" },
    { day: "Friday", startTime: "16:00", label: "HOPE F" },
    { day: "Friday", startTime: "17:00", label: "PR1" },
  ],
  KANT: [
    { day: "Monday", startTime: "07:45", label: "PAGBASA" },
    { day: "Tuesday", startTime: "07:45", label: "PAGBASA" },
    { day: "Wednesday", startTime: "07:45", label: "PAGBASA" },
    { day: "Thursday", startTime: "07:45", label: "PAGBASA" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "PR" },
    { day: "Tuesday", startTime: "08:45", label: "PR" },
    { day: "Wednesday", startTime: "08:45", label: "PR" },
    { day: "Thursday", startTime: "08:45", label: "PR" },
    { day: "Friday", startTime: "08:45", label: "PHYSCI" },
    { day: "Monday", startTime: "10:00", label: "BNC" },
    { day: "Tuesday", startTime: "10:00", label: "BNC" },
    { day: "Wednesday", startTime: "10:00", label: "HOPE F" },
    { day: "Thursday", startTime: "10:00", label: "BNC" },
    { day: "Friday", startTime: "10:00", label: "BNC" },
    { day: "Monday", startTime: "11:00", label: "BNC" },
    { day: "Tuesday", startTime: "11:00", label: "BNC" },
    { day: "Wednesday", startTime: "11:00", label: "PHYSCI" },
    { day: "Thursday", startTime: "11:00", label: "BNC" },
    { day: "Friday", startTime: "11:00", label: "BNC" },
    { day: "Monday", startTime: "13:00", label: "STAT" },
    { day: "Tuesday", startTime: "13:00", label: "STAT" },
    { day: "Wednesday", startTime: "13:00", label: "STAT" },
    { day: "Thursday", startTime: "13:00", label: "PHYSCI" },
    { day: "Friday", startTime: "13:00", label: "STAT" },
    { day: "Monday", startTime: "14:00", label: "UCSP" },
    { day: "Tuesday", startTime: "14:00", label: "UCSP" },
    { day: "Wednesday", startTime: "14:00", label: "UCSP" },
    { day: "Thursday", startTime: "14:00", label: "PHYSCI" },
    { day: "Friday", startTime: "14:00", label: "UCSP" },
    { day: "Monday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Thursday", startTime: "15:00", label: "READING & WRITING" },
  ],
};

export function findImagePrefillEntries(sectionName: string) {
  const key = (sectionName || "").toUpperCase().replace(/[^A-Z0-9]/g, "");
  // find a prefills entry where key contains the prefills key or vice versa
  const foundKey = Object.keys(imagePrefill).find((k) => key.includes(k) || k.includes(key));
  if (!foundKey) return [];
  return imagePrefill[foundKey] || [];
}

export default imagePrefill;
